#!/bin/bash
set -e

echo "[entrypoint] Starting MirzaBot Docker entrypoint..."

# ── Generate config.php from environment variables ──
CONFIG_FILE="/var/www/html/mirzabotconfig/config.php"

if [ ! -f "$CONFIG_FILE" ] || [ ! -s "$CONFIG_FILE" ]; then
    echo "[entrypoint] Generating config.php from environment variables..."
    cat > "$CONFIG_FILE" <<'CONFIGPHP'
<?php
// Auto-generated by docker-entrypoint.sh
$request_exec_timeout = null;
$dbhost = '{database_url}';
$dbname = '{database_name}';
$usernamedb = '{username_db}';
$passworddb = '{password_db}';
$options = [
    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    PDO::ATTR_EMULATE_PREPARES => false,
    PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci",
];
$dsn = "mysql:host=$dbhost;dbname=$dbname;charset=utf8mb4";
try {
    $pdo = new PDO($dsn, $usernamedb, $passworddb, $options);
} catch (\PDOException $e) {
    error_log("Database connection failed: " . $e->getMessage());
    die("error: database connection failed");
}
$APIKEY = '{API_KEY}';
$adminnumber = '{admin_number}';
$domainhosts = '{domain_name}';
$usernamebot = '{username_bot}';
?>
CONFIGPHP
fi

# Replace placeholders with env vars
sed -i "s|{database_url}|${DB_HOST:-db}|g" "$CONFIG_FILE"
sed -i "s|{database_name}|${DB_NAME:-mirzabot}|g" "$CONFIG_FILE"
sed -i "s|{username_db}|${DB_USER:-mirzabot}|g" "$CONFIG_FILE"
sed -i "s|{password_db}|${DB_PASS:-mirzabot}|g" "$CONFIG_FILE"
sed -i "s|{API_KEY}|${BOT_TOKEN}|g" "$CONFIG_FILE"
sed -i "s|{admin_number}|${ADMIN_ID}|g" "$CONFIG_FILE"
sed -i "s|{domain_name}|${DOMAIN}|g" "$CONFIG_FILE"
sed -i "s|{username_bot}|${BOT_USERNAME}|g" "$CONFIG_FILE"

echo "[entrypoint] config.php generated."

# ── Wait for MySQL to be ready ──
echo "[entrypoint] Waiting for MySQL at ${DB_HOST:-db}:3306..."
MAX_RETRIES=30
RETRY_COUNT=0
until php -r "
try {
    \$pdo = new PDO('mysql:host=${DB_HOST:-db};port=3306', '${DB_USER:-mirzabot}', '${DB_PASS:-mirzabot}', [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_TIMEOUT => 3,
    ]);
    echo 'Database connection successful!';
    exit(0);
} catch (PDOException \$e) {
    echo 'Database not ready: ' . \$e->getMessage() . PHP_EOL;
    exit(1);
}
" 2>/dev/null; do
    RETRY_COUNT=$((RETRY_COUNT + 1))
    if [ $RETRY_COUNT -ge $MAX_RETRIES ]; then
        echo "[entrypoint] ERROR: MySQL not ready after ${MAX_RETRIES} attempts. Exiting."
        exit 1
    fi
    echo "[entrypoint] MySQL not ready yet (attempt ${RETRY_COUNT}/${MAX_RETRIES}), waiting 2s..."
    sleep 2
done
echo "[entrypoint] MySQL is ready."

# ── Initialize database tables ──
echo "[entrypoint] Initializing database tables..."
php /var/www/html/mirzabotconfig/table.php 2>&1 || {
    echo "[entrypoint] WARNING: table.php had issues (may be first run, continuing...)"
}

# ── Set up Telegram webhook ──
if [ -n "$BOT_TOKEN" ] && [ -n "$DOMAIN" ]; then
    echo "[entrypoint] Setting Telegram webhook to https://${DOMAIN}/index.php"
    WEBHOOK_URL="https://${DOMAIN}/index.php"
    SECRET_TOKEN=$(openssl rand -hex 16 2>/dev/null || echo "dockersecret$(date +%s)")
    
    curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/setWebhook" \
        -F "url=${WEBHOOK_URL}" \
        -F "secret_token=${SECRET_TOKEN}" \
        -F "allowed_updates=[\"message\",\"callback_query\",\"chat_member\"]" \
        > /dev/null 2>&1 && echo "[entrypoint] Webhook set successfully." || \
        echo "[entrypoint] WARNING: Failed to set webhook (will retry on next restart)."
fi

# ── Set up cron ──
echo "[entrypoint] Setting up cron jobs..."
# Write cron entries to a temp file
cat > /tmp/mirzabot_cron <<CRON
# MirzaBot Cron Jobs (auto-generated)
# These run as www-data via the container's cron daemon

# Status day check
*/15 * * * * curl -s http://localhost/cronbot/statusday.php > /dev/null 2>&1

# Card cron
*/1 * * * * curl -s http://localhost/cronbot/croncard.php > /dev/null 2>&1

# Notifications service
*/1 * * * * curl -s http://localhost/cronbot/NoticationsService.php > /dev/null 2>&1

# Payment expire check
*/5 * * * * curl -s http://localhost/cronbot/payment_expire.php > /dev/null 2>&1

# Send message queue
*/1 * * * * curl -s http://localhost/cronbot/sendmessage.php > /dev/null 2>&1

# Plisio payment check
*/3 * * * * curl -s http://localhost/cronbot/plisio.php > /dev/null 2>&1

# Active config
*/1 * * * * curl -s http://localhost/cronbot/activeconfig.php > /dev/null 2>&1

# Disable config
*/1 * * * * curl -s http://localhost/cronbot/disableconfig.php > /dev/null 2>&1

# Iran pay 1
*/1 * * * * curl -s http://localhost/cronbot/iranpay1.php > /dev/null 2>&1

# Backup bot
0 */5 * * * curl -s http://localhost/cronbot/backupbot.php > /dev/null 2>&1

# Gift
*/2 * * * * curl -s http://localhost/cronbot/gift.php > /dev/null 2>&1

# Expire agent
*/30 * * * * curl -s http://localhost/cronbot/expireagent.php > /dev/null 2>&1

# On hold
*/15 * * * * curl -s http://localhost/cronbot/on_hold.php > /dev/null 2>&1

# Config test
*/2 * * * * curl -s http://localhost/cronbot/configtest.php > /dev/null 2>&1

# Uptime node
*/15 * * * * curl -s http://localhost/cronbot/uptime_node.php > /dev/null 2>&1

# Uptime panel
*/15 * * * * curl -s http://localhost/cronbot/uptime_panel.php > /dev/null 2>&1
CRON

# Install cron entries for www-data
crontab -u www-data /tmp/mirzabot_cron
rm /tmp/mirzabot_cron

echo "[entrypoint] Cron jobs configured."

# ── Ensure proper file permissions ──
chown -R www-data:www-data /var/www/html/mirzabotconfig
chmod -R 755 /var/www/html/mirzabotconfig
chmod -R 775 /var/www/html/mirzabotconfig/storage 2>/dev/null || true
chmod -R 775 /var/www/html/mirzabotconfig/data 2>/dev/null || true

# ── Start cron daemon in background ──
echo "[entrypoint] Starting cron daemon..."
cron -f -L 15 &
CRON_PID=$!
echo "[entrypoint] Cron daemon started (PID: $CRON_PID)"

# ── Execute the main command ──
echo "[entrypoint] Starting Apache..."
exec "$@"
